### ISSUE TITLE
Gate RPC問題

### ISSUE THREAD

**Issue by shihray** [liangdas/mqant#66]
我在啟動mqant後，時常會遇到該問題，請問有可能是什麼問題呢?
```
Gate rpc func(Push) error reflect: call of reflect.Value.Interface on zero Value
 ----Stack----
goroutine 184 [running]:
modules/mqant/rpc/base.(*RPCServer).runFunc.func3.1(0xc0003d2300, 0xc0001e42a0, 0xc000278c40, 0xc0001c9e30)
        D:/HonorIT/src/shihray/HonorServer/src/modules/mqant/rpc/base/rpc_server.go:282 +0x129
panic(0xa335c0, 0xc000278ee0)
        C:/Go/src/runtime/panic.go:513 +0x1c7
reflect.valueInterface(0x0, 0x0, 0x0, 0xa29901, 0xa06d01, 0xc0002a5100)
        C:/Go/src/reflect/value.go:983 +0x1a7
reflect.Value.Interface(0x0, 0x0, 0x0, 0xa06d40, 0xc0002a4e10)
        C:/Go/src/reflect/value.go:978 +0x4b
github.com/golang/protobuf/proto.makeMapMarshaler.func3(0xc00054c600, 0x183, 0x1f3, 0xc0004c23e0, 0x42, 0x4c7400, 0xc00054c600, 0x6d, 0x1f3, 0x0, ...)
        D:/HonorIT/src/github.com/golang/protobuf/proto/table_marshal.go:2340 +0x2dd
github.com/golang/protobuf/proto.(*marshalInfo).marshal(0xc0003e2540, 0xc00054c600, 0x6d, 0x1f3, 0xc0004c2370, 0x4e500, 0x1000000009f5580, 0x0, 0x1f3, 0xc00054c600, ...)
        D:/HonorIT/src/github.com/golang/protobuf/proto/table_marshal.go:270 +0x173
github.com/golang/protobuf/proto.(*InternalMes
```

**Comment by liangdas** [comment]
我还从来没有遇到过 你这个rpc Push 是不是传了空值？

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
